
USE Business;

SELECT * FROM dbo.customers;

ALTER TABLE dbo.customers
ALTER COLUMN review_rating DECIMAL(3,1);

-- total revenue generated by male and female

SELECT gender,SUM(purchase_amount) as revenue
FROM dbo.customers
GROUP BY gender;

--used discount but still spent more than average purchase amount

SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied = 'YES' AND purchase_amount >= (
select AVG(purchase_amount) from customers)

-- top 5 higest avg rating of product 

SELECT TOP 5
    item_purchased,
    CAST(AVG(review_rating) AS DECIMAL(10,2)) AS [Average Product Rating]
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;

--average Purchase Amounts between Standard and Express Shipping.

SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS Average_Purchase_Amount
FROM customers
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- 5 products have the highest percentage of purchases with discounts applied

SELECT TOP 5
    item_purchased,
    CAST(
        ROUND(
            100.0 * SUM(
                CASE
                    WHEN discount_applied = 'Yes' THEN 1
                    ELSE 0
                END
            ) / COUNT(*),
            2
        ) AS DECIMAL(5,2)
    ) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC;

-- Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customers
)

SELECT
    customer_segment,
    COUNT(*) AS [Number of Customers]
FROM customer_type
GROUP BY customer_segment;


--  What are the top 3 most purchased products within each category? 

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

--ustomers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- the revenue contribution of each age group

SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;


SELECT @@VERSION;